# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/RAM7995/webapp2-k8s.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
